### ISSUE TITLE
Intermod Interaction: Node Dynamo + Ethereal Shard

### ISSUE THREAD

**Issue by lamialily** [theflogat/Technomancy#124]
I've discovered a rather powerful combination between two mods -- by using one of Thaumic Horizons' ethereal shards with a node dynamo from Technomancy, you can generate power on several more orders of magnitude from an energised node than an unenergised one, and at a constant flow at that.

My tests were with an ordo/perditio node on the order of about 40 vis each. Ordinarily not enough to power a regular node dynamo; by energising it, placing a couple of ethereal shards with ordo/perditio essences and then installing potency crystals, I was getting 640RF/t power with only minimal drain on the centivis output of the energised node, and could probably generate several thousands more before I started seeing an actual impact on the CV output.

I recommend adding in checks to see if the vis source of a node dynamo is an ethereal shard should TH be installed, and if so applying a configurable multiplier to vis costs from it... Or just refusing to draw from it entirely.

**Comment by theflogat** [comment]
I don't really think it's problem.

**Comment by Mordenkainen** [comment]
I don't have a lot of experience with TH yet, so can you explain what the Ethereal Shards do?

From your description it sounds like they convert centivs into "node aura" that can be used to do things like recharge wands and such, but in this case you are using them to power a Dynamo.

I do not really see a problem with this interaction from Technomancys side. If my guess as to the function of the shards is correct, and they recharge at a faster rate then a bright node, then it would seem the issue is with the shards implementation because that behavior could unbalance many different mechanics, not just this one. The "right" fix would be for TH to limit the throughput of the shards to around what a bright node can handle.

**Comment by lamialily** [comment]
You are on the dot there, Mordenkainen. Unfortunately TH doesn't even have a config file yet, and the author has not provided any means of issue tracking for it, so I'm having my doubts as to whether I'd have any luck getting them to do anything on their end.

**Comment by Mordenkainen** [comment]
Actually, early in the life of that mod I found a name conflict with technomancy. I posted about it on the mods curse page and the author fixed it in less thank a day. You might try that.

**Comment by lamialily** [comment]
Alright, can do. Thanks for hearing me out.
