### ISSUE TITLE
Hippie Engine 

### ISSUE THREAD

**Issue by Mattabase** [theflogat/Technomancy#154]
It does not producer power when give a redstone signal, and crashed when putting a conduit over it. 

https://dl.dropboxusercontent.com/u/15990261/ShareX/2015/09/crash-2015-09-07_22.48.33-server.txt

You also can not rotate it.

**Comment by Mordenkainen** [comment]
I suspect it's because of the Beta version of Ender IO, since it's actually Ender IO crashing there.

The Dynamo definitely implements this interface, so I'm not sure why EIO is screaming about it. Is it possible for your to check one of the other Technomancy Dynamos to see if they behave the same way? Also would it be possible for you to check a different energy transport, like an Energy Duct or some such?

What tool are you trying to rotate it with?

**Comment by Mattabase** [comment]
Use all the wrenches I had installed. TE to BC

The crash has since been figured out, one of the mods installed was using a really old COFH APi.

I will give it shot again, with better detail as to rotating this time. Thanks for the response. =)

**Comment by Mattabase** [comment]
https://dl.dropboxusercontent.com/u/15990261/ShareX/2015/09/2015-09-08_13-12-58.mp4

Engine stuff

**Comment by Mattabase** [comment]
The Essentia Dynamo seems to work.

**Comment by Mordenkainen** [comment]
Ok, the video helps a lot... the dynamo will only rotate to connect to valud power destinations. So, in your case you only have the single capacitor, there is no other "valid" orientation to rotate to.

Also, the dynamo draws power directly from mana pools. No mana spreader is needed. Try moving the dynamo one block closer to the mana pool and see if that gets things running.
