### ISSUE TITLE
Eldritch Consumer & Thaumic Energistics

### ISSUE THREAD

**Issue by Mohron** [theflogat/Technomancy#168]
Version: **0.11.1** via Resonant Rise 3.2.7.2-RC Project Flux

When originally setting up the Eldritch Consumer, I tried to use an essentia import bus from Thaumic energistics to remove the essentia. This does not work even though it makes no sense to not work in this way. Instead I had to connect the Eldritch Consumer via essintia tubes to a warded jar for the essentia import bus to attach to. I have attached a screenshot for reference.

![image](https://cloud.githubusercontent.com/assets/3623122/10797386/b8436eb6-7da2-11e5-873c-f698085cb14c.png)

**Comment by Mordenkainen** [comment]
Looking at Thaumic Energistics source and it would appear @Nividica added a whitelist of what Thaumic Energistics is allowed to insert and extract from... I suspect there are now quite a bit of mods that Thaumic Energistics will no longer work with, since it only whielists Thau
mcraft items.

Should be simple to fix, but I'm not sure anymore 1.7.10 releases are being done.
