### ISSUE TITLE
pretty big bug, never even seen one like this before, maybe ASM related

### ISSUE THREAD

**Issue by plaguewolf** [theflogat/Technomancy#174]
instance setup;

latest recommended forge [1558]

technomancy 0.12.2
minefactoryreloaded 2.8.1B1-160
[required for MFR]
cofhcore 3.1.0B1-321
thermal dynamics 1.1.0-161
thermal expansion 4.1.0B1-234
thermal foundation 1.2.1-109

error: http://pastebin.com/TBh8kDP4

**Comment by plaguewolf** [comment]
it is, in fact, MFR, thats causing it, as rolling back to my older version it loads

working on MFR 2.8.1B1-131

testing all version after that in revers order to determine what change broke things

also, made a post on MFR about it, just sayin

**Comment by theflogat** [comment]
Thanks. Will keep this issue open for reference.

**Comment by Manuepolis23** [comment]
is this issue gonna be resolved?

**Comment by Mordenkainen** [comment]
Once the cause is figured out.....

4 days before a "are you gonna fix this" seems a little impatient.

In any case, looking at the MFR code, and what @Skyboy had to say about the issue, it almost seems the java compiler is outputting slightly different code after he updated to Java 1.7.

I will have to see if there is anything I can do to make it work with both versions, or perhaps some way to check the existing bytecode before I start patching so as to abort without causing the error.
