### ISSUE TITLE
WorldHelper.isFull(IAspectContainer cont)

### ISSUE THREAD

**Issue by theflogat** [theflogat/Technomancy#79]
Need to fix by having the same thing at the beggining and at the end (using cont.getAspects()).
For example with Void Jars, will lack 1 aspect if was at 64.

**Comment by Mordenkainen** [comment]
Referencing IAspectContainer from a common static class breaks the mod API isolation. I believe after this change the mod will probably no longer run without Thaumcraft :(.

It's ok in a non-static method, as long as you never call the method. But the classloader resolves all references in static methods of a class when the class is loaded for any reference. I have not tried this but I believe that without Thaumcraft installed, the mod now crashes when any method in WorldHelper is called.

It would be best to keep things like this in the compatibility handler for the mod it belongs to since that is only loaded when the mod is.

**Comment by theflogat** [comment]
Ok. Will do.

**Comment by Mordenkainen** [comment]
Also, a good way to check might be checking if the container has any "suction". Most aspect containers are also IEssentiaTransport and set their suction to "0" when full.

There are a few exceptions like alembics (suction always 0) and void jars (suction never 0), but those could be handled with some special case code, I.E. cast to an object of that type and directly compare contents with a known max value.
